package:
  name: cilium-cli
  version: 0.15.9
  epoch: 0
  description: CLI to install, manage & troubleshoot Kubernetes clusters running Cilium
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go
      - git

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/cilium/cilium-cli
      tag: v${{package.version}}
      expected-commit: b649f968acb438124abd426a5d5eac7b10e29992
      destination: cilium-cli

  - runs: |
      cd cilium-cli
      make install
      install -Dm755  /usr/local/bin/cilium ${{targets.destdir}}/usr/bin/cilium

  - uses: strip

update:
  enabled: true
  github:
    identifier: cilium/cilium-cli
    strip-prefix: v
