package:
  name: k8s-sidecar
  version: 1.25.1
  epoch: 2
  description: "container intended to run inside a kubernetes cluster to collect config maps with a specified label and store the included files in a local folder"
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - python3

environment:
  contents:
    packages:
      - wolfi-base
      - busybox
      - ca-certificates-bundle
      - build-base
      - python3
      - py3-pip
      - py3-setuptools

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/kiwigrid/k8s-sidecar
      tag: ${{package.version}}
      expected-commit: 1d7a3566c129b8f7c0def292e9407ee856a9e0d4

  - runs: |
      mkdir -p ${{targets.destdir}}/usr/share/app

      cd src
      # Mitigate CVE-2022-40897 / GHSA-r9hx-vwmv-q579
      pip install --upgrade setuptools
      pip3 install --no-cache-dir -r requirements.txt --prefix=/usr --root="${{targets.destdir}}"
      cd ..
      mv src/* ${{targets.destdir}}/usr/share/app

      find ${{targets.destdir}} \( -type d -a -name test -o -name tests \) -o \( -type f -a -name '*.pyc' -o -name '*.pyo' \) -exec rm -rf '{}' \+

  - uses: strip

update:
  enabled: true
  github:
    identifier: kiwigrid/k8s-sidecar
    use-tag: true
